### ISSUE TITLE
Add Gradle Builds

### ISSUE THREAD

**Issue by mikesmithson** [kkapelon/java-testing-with-spock#11] opened 2016-09-10 02:30 UTC
Hi,
 I have taken an interest in Spock and have looked to the Manning book for learning about it. I have forked your repository and have started working on providing Gradle build scripts. Once completed, I would like to make a pull request to have the Gradle build scripts merged into your repo. Is this something you would find of value?

Thanks,

Mike

**Comment by kkapelon** [comment] 2016-09-10 10:43
Hello Mike. 

Sure! No problem. Actually for some of the starting chapters I had Gradle scripts as well (look at the git history). I then removed them because I didn't want to confuse the reader too much. My imaginary reader was a Java developer that knows only Java/JUnit/Maven and nothing else. Attempting to teach Groovy/Gradle/Spock in a single book would be impossible.

But of course, times have changed! So yes, if you can add Gradle support I would merge it. But keep in mind that the pom files have to stay as well and they need to continue working (the book is based on them). So you should not change the project structure in the process of adding Gradle support. The final code should be built with either Maven or Gradle.

Notice also, that by design, I have made all chapters completely independent. Anybody can check out any chapter on its own and start working on it. I think it is a nice practice to follow, so if you can achieve the same thing with Gradle I would be grateful (but I am open to a different opinion)

Let me know of your thoughts and we can discuss this more if you have something different in mind.

Many thanks for your interest in the book.

Kostis

**Comment by mikesmithson** [comment] 2016-09-10 12:25
Hi Kostis,
I have kept the maven pom.xml files and the project structure assuming that you didn't want to remove Maven support. I also made independent gradle scripts for each chapter which are close copies of one another. I could have gone down the route of doing a multi-project build where each chapter is a module that was controlled by a centrally configured gradle script but thought it would add more confusion for newbies who simply want to just run the test task on each chapter. Another thing I did was to create gradle wrapper files in each chapter so that the reader would not have to be burdened with downloading and configuring gradle, they simply can invoke gradlew at each chapter's root directory.

**Comment by kkapelon** [comment] 2016-09-11 11:38
Excellent! That is exactly what I was thinking.  Awaiting the PR then....

**Comment by mikesmithson** [comment] 2016-09-12 01:51
Hi again Kotis,
 I am mostly complete with everything, however, I am having a couple of issues with two of the three projects in chapter 7. The spring-standalone-project has failing tests where there is an issue with the Product table not being mapped. I am unsure why this is since the Gradle dependencies are pretty much the same as the Maven dependencies. I am a bit stumped right now. The other issue is with the web-ui-example, I don't believe that the version of Firefox I have installed on my Mac (48.0) is compatible with any of the selenium-firefox drivers. If you have time to take a look at the two aforementioned projects in chapter 7 and if you see anything that is obviously mis-configured, that would help a lot. 

Thanks....

**Comment by kkapelon** [comment] 2016-09-13 18:28
Ok. I will check the chapters. Will you create the PR as well, so that I can comment directly on it if I find something?

Kostis

**Comment by kkapelon** [comment] 2016-09-13 18:59
Another problem I noticed is in chapter two. There a file NormalAssert.java contains asserts that fail (on purpose). This file is ignored by Maven (as it does not end in *Test.java) but is picked by Gradle (and thus the whole build fails)

This file should be ignored by Gradle as well.

**Comment by kkapelon** [comment] 2016-09-13 19:24
I found the problem with spring-standalone. Gradle places resources and classes in different folders. JPA however picks classes and persistence.xml from the same folder and fails to find them during a Gradle test.

If you instruct Gradle to place the resources along with the classes everything works fine. I have tried it locally and it works.

**Comment by mikesmithson** [comment] 2016-09-13 19:30
Thanks, Kostis. I updated the build.gradle file for chapter 2. Let me know how it looks. You are saying in your second message that persistence.xml should be placed in the classes directory?

**Comment by kkapelon** [comment] 2016-09-13 19:51
Yes, exactly

See gradle discussion here (last answer is a workaround as well)
https://discuss.gradle.org/t/resources-from-src-main-resources-not-included-for-test/6983/2

Although ideally we need to include the persistence.xml in the test and the reduced-context (and not the normal context).

I will look into the Firefox drivers, later this week.

Kostis

**Comment by mikesmithson** [comment] 2016-09-13 20:19
That's exactly what I did. I was also possibly considering a custom task that just copies those files only and the remainder of the files in the resources directory are untouched.

**Comment by mikesmithson** [comment] 2016-09-14 03:01
Hi Kostis,
 I refactored the web-ui-example, using the ChromeDriver that is in the project directory. This makes the selenium tests less reliant on the client browser that is installed and not having to worry whether or not the version of the browser is compatible with the drivers that project is reliant upon in its dependency tree. There were changes in one test class and the pom.xml as well as the build.gradle file. The only thing I am not sure of is when someone is running maven on a windows machine. If I rename the chromedriver.exe to just chromedriver in the windows directory, do you think that will cause any harm? I will have to check it out.

**Comment by kkapelon** [comment] 2016-09-14 17:49
Hello Mike.

I added some comments on your PR.
In general the book already mentions Firefox and we should not change it.

We need to find a better solution there. I am bit pressed with time this period to look this myself deeper but readers should read about Firefox in the book and see Firefox when they run Maven

Kostis

**Comment by mikesmithson** [comment] 2016-09-18 20:05
Hi Kostis,
 I made the changes based on your comments. The CI builds run green for both Maven and Gradle. Let me know what you think.

**Comment by kkapelon** [comment] 2016-09-19 17:52
Excellent!

I have no further comment. As a final step could you please "squash" your git commits into a single one called "Adding Gradle support" (or something similar)?

The current PR has a lot of intermediate commit messages until the final result.

Other than that the content of the PR is ready to be merged.

Many thanks for your diligence.

Kostis

**Comment by mikesmithson** [comment] 2016-09-19 17:56
Hi Kostis, 
Sure, I can squash the commits for you. Thanks for your patience with me.

**Comment by kkapelon** [comment] 2016-09-20 20:33
No worries Mike!

You have actually saved me a lot of time. Adding Gradle support was in my huge TODO list anyway.
I can now strike it out, thanks to you...

Pull request was merged.

Kostis

**Closed as completed by kkapelon** 2016-09-20 20:33 UTC
